# =============================================================================
# WISPr Automation
# Repository : sac-mgerencs-wispr-automation
# Author     : Wade Gerencser (mgerencs)
# Copyright  : (c) 2026 Wade Gerencser.
# License    : MIT — see LICENSE
# =============================================================================
---
all:
  children:
    wlc:
      hosts:
        wlc01:
          ansible_host: 192.0.2.1
      vars:
        ansible_network_os: cisco.ios.ios
        ansible_connection: network_cli
        ansible_user: admin
        ansible_password: "{{ vault_wlc_password }}"
